adapt {un,}export signatures
fixes:

vinput.c:304:22: error: initialization of ‘ssize_t (*)(const struct class *, const struct class_attribute *, const char *, size_t)’ {aka ‘long int (*)(const struct class *, const struct class_attribute *, const char *, long unsigned int)’} from incompatible pointer type ‘ssize_t (*)(struct class *, struct class_attribute *, const char *, size_t)’ {aka ‘long int (*)(struct class *, struct class_attribute *, const char *, long unsigned int)’}

the signature changed in 75a2d42 "driver core: class: mark the struct class for sysfs callbacks as constant"